// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/google/wire"
	repositories2 "lovers/internal/domain/repositories"
	"lovers/internal/infrastructure/repositories"
	auth2 "lovers/internal/presentation/auth"
	"lovers/internal/shared/config"
	"lovers/internal/shared/infrastructure/sharedAws"
	"lovers/internal/use_cases/auth"
)

// Injectors from wire.go:

func Initialize(client *sharedAws.CognitoClient, cfg *config.CognitoConfig) *AuthSet {
	authRepositoryImpl := ProvideAuthRepository(client, cfg)
	signUp := auth.NewSignUp(authRepositoryImpl)
	authController := auth2.NewAuthController(signUp)
	authSet := &AuthSet{
		AuthController: authController,
	}
	return authSet
}

// wire.go:

func ProvideAuthRepository(client *sharedAws.CognitoClient, cognitoConfig *config.CognitoConfig) *repositories.AuthRepositoryImpl {
	repository := repositories.NewAuthRepositoryImpl(client, cognitoConfig)
	return repository
}

var authRepositorySet = wire.NewSet(
	ProvideAuthRepository, wire.Bind(new(repositories2.AuthRepository), new(*repositories.AuthRepositoryImpl)),
)

var signUpSet = wire.NewSet(auth.NewSignUp)

var authControllerSet = wire.NewSet(auth2.NewAuthController)

type AuthSet struct {
	AuthController *auth2.AuthController
}
