// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package template

import (
	"github.com/google/wire"
	repositories2 "lovers/internal/domain/repositories"
	"lovers/internal/infrastructure/repositories"
	template2 "lovers/internal/presentation/template"
	"lovers/internal/shared/infrastructure/db"
	"lovers/internal/usecases/template"
)

// Injectors from wire.go:

func Initialize(d *db.DbClient) *TemplateSet {
	templateRepositoryImpl := ProvideTemplateRepository(d)
	templateCreate := template.NewTemplateCreate(templateRepositoryImpl)
	templateController := template2.NewTemplateController(templateCreate)
	templateSet := &TemplateSet{
		TemplateController: templateController,
	}
	return templateSet
}

// wire.go:

func ProvideTemplateRepository(d *db.DbClient) *repositories.TemplateRepositoryImpl {
	repository := repositories.NewTemplateRepository(d)
	return repository
}

var templateRepositorySet = wire.NewSet(
	ProvideTemplateRepository, wire.Bind(new(repositories2.TemplateRepository), new(*repositories.TemplateRepositoryImpl)),
)

var createSet = wire.NewSet(template.NewTemplateCreate)

var templateControllerSet = wire.NewSet(template2.NewTemplateController)

type TemplateSet struct {
	TemplateController *template2.TemplateController
}
