// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package aws

import (
	"context"
	"github.com/google/wire"
	"log/slog"
	"lovers/internal/shared/infrastructure/aws"
)

// Injectors from wire.go:

func Initialize(ctx context.Context, logger *slog.Logger) (*AwsSet, error) {
	cognitoClient, err := aws.InitCognitoClient(ctx, logger)
	if err != nil {
		return nil, err
	}
	parameterStoreClient, err := aws.InitParameterStoreClient(ctx, logger)
	if err != nil {
		return nil, err
	}
	awsSet := &AwsSet{
		Cognito:        cognitoClient,
		ParameterStore: parameterStoreClient,
	}
	return awsSet, nil
}

// wire.go:

var cognitoSet = wire.NewSet(aws.InitCognitoClient)

var parameterStoreSet = wire.NewSet(aws.InitParameterStoreClient)

type AwsSet struct {
	Cognito        *aws.CognitoClient
	ParameterStore *aws.ParameterStoreClient
}
