// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/google/wire"
	repositories2 "lovers/internal/domain/repositories"
	"lovers/internal/infrastructure/repositories"
	user2 "lovers/internal/presentation/user"
	"lovers/internal/shared/infrastructure/db"
	"lovers/internal/usecases/user"
)

// Injectors from wire.go:

func Initialize(d *db.DbClient) *UserSet {
	userRepositoryImpl := ProvideUserRepository(d)
	userRegistration := user.NewUserRegistration(userRepositoryImpl)
	userController := user2.NewUserController(userRegistration)
	userSet := &UserSet{
		UserController: userController,
	}
	return userSet
}

// wire.go:

func ProvideUserRepository(d *db.DbClient) *repositories.UserRepositoryImpl {
	repository := repositories.NewUserRepository(d)
	return repository
}

var userRepositorySet = wire.NewSet(
	ProvideUserRepository, wire.Bind(new(repositories2.UserRepository), new(*repositories.UserRepositoryImpl)),
)

var registrationSet = wire.NewSet(user.NewUserRegistration)

var userControllerSet = wire.NewSet(user2.NewUserController)

type UserSet struct {
	UserController *user2.UserController
}
