// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package expense

import (
	"github.com/google/wire"
	repositories2 "lovers/internal/domain/repositories"
	"lovers/internal/infrastructure/port"
	"lovers/internal/infrastructure/repositories"
	"lovers/internal/infrastructure/services"
	expense2 "lovers/internal/presentation/expense"
	"lovers/internal/shared/infrastructure/db"
	"lovers/internal/usecases/expense"
	port2 "lovers/internal/usecases/port"
	"lovers/internal/usecases/port/query"
)

// Injectors from wire.go:

func Initialize(d *db.DbClient) *ExpenseSet {
	expenseRepositoryImpl := ProvideExpenseRepository(d)
	groupQueryServiceImpl := ProvideGroupQueryService(d)
	transactionManagerImpl := ProvideTransactionManager(d)
	expenseCreate := expense.NewExpenseCreate(expenseRepositoryImpl, groupQueryServiceImpl, transactionManagerImpl)
	expenseController := expense2.NewExpenseController(expenseCreate)
	expenseSet := &ExpenseSet{
		ExpenseController: expenseController,
	}
	return expenseSet
}

// wire.go:

func ProvideExpenseRepository(d *db.DbClient) *repositories.ExpenseRepositoryImpl {
	repository := repositories.NewExpenseRepository(d)
	return repository
}

var expenseRepositorySet = wire.NewSet(
	ProvideExpenseRepository, wire.Bind(new(repositories2.ExpenseRepository), new(*repositories.ExpenseRepositoryImpl)),
)

func ProvideGroupQueryService(d *db.DbClient) *services.GroupQueryServiceImpl {
	service := services.NewGroupQueryService(d)
	return service
}

var groupQueryServiceSet = wire.NewSet(
	ProvideGroupQueryService, wire.Bind(new(query.GroupQueryService), new(*services.GroupQueryServiceImpl)),
)

func ProvideTransactionManager(d *db.DbClient) *port.TransactionManagerImpl {
	manager := port.NewTransactionManager(d)
	return manager
}

var transactionManagerSet = wire.NewSet(
	ProvideTransactionManager, wire.Bind(new(port2.TransactionManager), new(*port.TransactionManagerImpl)),
)

var createSet = wire.NewSet(expense.NewExpenseCreate)

var expenseControllerSet = wire.NewSet(expense2.NewExpenseController)

type ExpenseSet struct {
	ExpenseController *expense2.ExpenseController
}
